name: flutter_screenshot_switcher
description: A flutter plugin that allows to enable &#x2F; disable screenshots.
version: 1.0.1
author: Jeroen Trappers <jeroen.trappers@gmail.com>
homepage: https://github.com/jeroentrappers/flutter_screenshot_switcher

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.appmire.flutter_screenshot_switcher
    pluginClass: FlutterScreenshotSwitcherPlugin

